# Generated by Django 3.1 on 2020-08-10 22:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogcontent', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='comment',
        ),
    ]
